In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import plotly.graph_objects as go

In [25]:
df = pd.read_csv(r"C:\Users\omare\OneDrive\Documents\anaconda_projects\Training_data_sets\file.csv")
df

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Avg_Price,Delivery_Charges,Coupon_Status,GST,Date,Offline_Spend,Online_Spend,Month,Coupon_Code,Discount_pct
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,153.71,6.5,Used,0.1,1/1/2019,4500.0,2424.5,1,ELEC10,10.0
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,153.71,6.5,Used,0.1,1/1/2019,4500.0,2424.5,1,ELEC10,10.0
2,2,17850.0,M,Chicago,12.0,16696.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,122.77,6.5,Not Used,0.1,1/1/2019,4500.0,2424.5,1,ELEC10,10.0
3,3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,81.50,6.5,Clicked,0.1,1/1/2019,4500.0,2424.5,1,ELEC10,10.0
4,4,17850.0,M,Chicago,12.0,16700.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,153.71,6.5,Clicked,0.1,1/1/2019,4500.0,2424.5,1,ELEC10,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52950,52950,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Gift Cards,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,GC20,20.0
52951,52951,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Notebooks & Journals,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,NJ20,20.0
52952,52952,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Android,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,AND10,10.0
52953,52953,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Android,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,AND20,20.0
52954,52954,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Android,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,AND30,30.0

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52955 entries, 0 to 52954
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           52955 non-null  int64
 1   CustomerID           52924 non-null  float64
 2   Gender               52924 non-null  object
 3   Location             52924 non-null  object
 4   Tenure_Months        52924 non-null  float64
 5   Transaction_ID       52924 non-null  float64
 6   Transaction_Date     52924 non-null  object
 7   Product_SKU          52924 non-null  object
 8   Product_Description  52924 non-null  object
 9   Product_Category     52955 non-null  object
 10  Quantity             52924 non-null  float64
 11  Avg_Price            52924 non-null  float64
 12  Delivery_Charges     52924 non-null  float64
 13  Coupon_Status        52924 non-null  object
 14  GST                  52924 non-null  float64
 15  Date                 52924 non-null  object
 16  Offline_Spend        52924 non-null  float64
 17  Online_Spend         52924 non-null  float64
 18  Month                52955 non-null  int64
 19  Coupon_Code          52555 non-null  object
 20  Discount_pct         52555 non-null  float64
dtypes: float64(10), int64(2), object(9)
memory usage: 8.5+ MB

In [27]:
df.describe(include= 'all')

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Avg_Price,Delivery_Charges,Coupon_Status,GST,Date,Offline_Spend,Online_Spend,Month,Coupon_Code,Discount_pct
count,52955.000000,52924.00000,52924,52924,52924.000000,52924.000000,52924,52924,52924,52955,...,52924.000000,52924.000000,52924,52924.000000,52924,52924.000000,52924.000000,52955.000000,52555,52555.000000
unique,NaN,NaN,2,5,NaN,NaN,365,1145,404,21,...,NaN,NaN,3,NaN,365,NaN,NaN,NaN,48,NaN
top,NaN,NaN,F,Chicago,NaN,NaN,2019-11-27,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Apparel,...,NaN,NaN,Clicked,NaN,11/27/2019,NaN,NaN,NaN,SALE20,NaN
freq,NaN,NaN,33007,18380,NaN,NaN,335,3511,3511,18126,...,NaN,NaN,26926,NaN,335,NaN,NaN,NaN,6373,NaN
mean,26477.000000,15346.70981,NaN,NaN,26.127995,32409.825675,NaN,NaN,NaN,NaN,...,52.237646,10.517630,NaN,0.137462,NaN,2830.914141,1893.109119,6.652800,NaN,19.953382
std,15286.936089,1766.55602,NaN,NaN,13.478285,8648.668977,NaN,NaN,NaN,NaN,...,64.006882,19.475613,NaN,0.045825,NaN,936.154247,807.014092,3.333664,NaN,8.127108
min,0.000000,12346.00000,NaN,NaN,2.000000,16679.000000,NaN,NaN,NaN,NaN,...,0.390000,0.000000,NaN,0.050000,NaN,500.000000,320.250000,1.000000,NaN,10.000000
25%,13238.500000,13869.00000,NaN,NaN,15.000000,25384.000000,NaN,NaN,NaN,NaN,...,5.700000,6.000000,NaN,0.100000,NaN,2500.000000,1252.630000,4.000000,NaN,10.000000
50%,26477.000000,15311.00000,NaN,NaN,27.000000,32625.500000,NaN,NaN,NaN,NaN,...,16.990000,6.000000,NaN,0.180000,NaN,3000.000000,1837.870000,7.000000,NaN,20.000000
75%,39715.500000,16996.25000,NaN,NaN,37.000000,39126.250000,NaN,NaN,NaN,NaN,...,102.130000,6.500000,NaN,0.180000,NaN,3500.000000,2425.350000,9.000000,NaN,30.000000
max,52954.000000,18283.00000,NaN,NaN,50.000000,48497.000000,NaN,NaN,NaN,NaN,...,355.740000,521.360000,NaN,0.180000,NaN,5000.000000,4556.930000,12.000000,NaN,30.000000

In [28]:
df.isnull().sum()

Unnamed: 0               0
CustomerID              31
Gender                  31
Location                31
Tenure_Months           31
Transaction_ID          31
Transaction_Date        31
Product_SKU             31
Product_Description     31
Product_Category         0
Quantity                31
Avg_Price               31
Delivery_Charges        31
Coupon_Status           31
GST                     31
Date                    31
Offline_Spend           31
Online_Spend            31
Month                    0
Coupon_Code            400
Discount_pct           400
dtype: int64

In [29]:
df.shape

(52955, 21)

In [30]:
df.columns

Index(['Unnamed: 0', 'CustomerID', 'Gender', 'Location', 'Tenure_Months',
       'Transaction_ID', 'Transaction_Date', 'Product_SKU',
       'Product_Description', 'Product_Category', 'Quantity', 'Avg_Price',
       'Delivery_Charges', 'Coupon_Status', 'GST', 'Date', 'Offline_Spend',
       'Online_Spend', 'Month', 'Coupon_Code', 'Discount_pct'],
      dtype='object')

In [31]:
df = df.dropna(subset= ['Unnamed: 0', 'CustomerID', 'Gender', 'Location', 'Tenure_Months',
       'Transaction_ID', 'Transaction_Date', 'Product_SKU',
       'Product_Description', 'Quantity', 'Avg_Price',
       'Delivery_Charges', 'Coupon_Status', 'GST', 'Date', 'Offline_Spend',
       'Online_Spend'])

In [32]:
df.isnull().sum()

Unnamed: 0               0
CustomerID               0
Gender                   0
Location                 0
Tenure_Months            0
Transaction_ID           0
Transaction_Date         0
Product_SKU              0
Product_Description      0
Product_Category         0
Quantity                 0
Avg_Price                0
Delivery_Charges         0
Coupon_Status            0
GST                      0
Date                     0
Offline_Spend            0
Online_Spend             0
Month                    0
Coupon_Code            400
Discount_pct           400
dtype: int64

In [33]:
df.columns = df.columns.str.lower()
df.columns

Index(['unnamed: 0', 'customerid', 'gender', 'location', 'tenure_months',
       'transaction_id', 'transaction_date', 'product_sku',
       'product_description', 'product_category', 'quantity', 'avg_price',
       'delivery_charges', 'coupon_status', 'gst', 'date', 'offline_spend',
       'online_spend', 'month', 'coupon_code', 'discount_pct'],
      dtype='object')

In [34]:
df = df.rename(columns= {'customerid' : 'customer_id'})
df.columns

Index(['unnamed: 0', 'customer_id', 'gender', 'location', 'tenure_months',
       'transaction_id', 'transaction_date', 'product_sku',
       'product_description', 'product_category', 'quantity', 'avg_price',
       'delivery_charges', 'coupon_status', 'gst', 'date', 'offline_spend',
       'online_spend', 'month', 'coupon_code', 'discount_pct'],
      dtype='object')

In [35]:
df.tail(10)

,unnamed: 0,customer_id,gender,location,tenure_months,transaction_id,transaction_date,product_sku,product_description,product_category,...,avg_price,delivery_charges,coupon_status,gst,date,offline_spend,online_spend,month,coupon_code,discount_pct
52914,52914,14031.0,F,Chicago,17.0,19075.0,2019-01-29,GGOEGBPB081999,UpCycled Bike Saddle Bag,Accessories,...,51.57,6.5,Clicked,0.10,1/29/2019,700.0,836.13,1,ACC10,10.0
52915,52915,15002.0,M,Chicago,41.0,23797.0,2019-03-22,GGOEGGCX056299,Gift Card - $25.00,Gift Cards,...,25.00,0.0,Clicked,0.05,3/22/2019,2000.0,2523.41,3,GC30,30.0
52916,52916,15002.0,M,Chicago,41.0,23798.0,2019-03-22,GGOEGGCX056299,Gift Card - $25.00,Gift Cards,...,25.00,0.0,Used,0.05,3/22/2019,2000.0,2523.41,3,GC30,30.0
52917,52917,15002.0,M,Chicago,41.0,23799.0,2019-03-22,GGOEGGCX056299,Gift Card - $25.00,Gift Cards,...,25.00,0.0,Clicked,0.05,3/22/2019,2000.0,2523.41,3,GC30,30.0
52918,52918,15002.0,M,Chicago,41.0,23800.0,2019-03-22,GGOEGGCX056299,Gift Card - $25.00,Gift Cards,...,25.00,0.0,Clicked,0.05,3/22/2019,2000.0,2523.41,3,GC30,30.0
52919,52919,13155.0,F,California,8.0,22504.0,2019-03-10,GGOEGGCX056399,Gift Card - $250.00,Gift Cards,...,250.00,0.0,Clicked,0.05,3/10/2019,2500.0,1294.22,3,GC30,30.0
52920,52920,18077.0,M,Chicago,34.0,24250.0,2019-03-28,GGOEGGCX056299,Gift Card - $25.00,Gift Cards,...,25.00,0.0,Used,0.05,3/28/2019,2000.0,1066.12,3,GC30,30.0
52921,52921,16085.0,M,California,15.0,39991.0,2019-10-06,GGOEGOCD078399,Google Leather Perforated Journal,Notebooks & Journals,...,10.80,6.0,Clicked,0.05,10/6/2019,3000.0,2230.76,10,NJ10,10.0
52922,52922,16085.0,M,California,15.0,39991.0,2019-10-06,GGOEGOCR078499,Google Spiral Leather Journal,Notebooks & Journals,...,9.60,6.0,Used,0.05,10/6/2019,3000.0,2230.76,10,NJ10,10.0
52923,52923,13659.0,F,Chicago,8.0,39998.0,2019-10-06,GGOEGOCC077999,Google Spiral Journal with Pen,Notebooks & Journals,...,5.59,6.5,Not Used,0.05,10/6/2019,3000.0,2230.76,10,NJ10,10.0

In [36]:
df = df.drop(columns= ['unnamed: 0'])

In [37]:
df['coupon_code'] = df['coupon_code'].fillna('No coupon code provided!')
df['discount_pct'] = df['discount_pct'].fillna(0)

In [38]:
df.isnull().sum()

customer_id            0
gender                 0
location               0
tenure_months          0
transaction_id         0
transaction_date       0
product_sku            0
product_description    0
product_category       0
quantity               0
avg_price              0
delivery_charges       0
coupon_status          0
gst                    0
date                   0
offline_spend          0
online_spend           0
month                  0
coupon_code            0
discount_pct           0
dtype: int64

In [39]:
df = df.rename(columns= {'product_description' : 'product_name','avg_price' : 'price', 'gst' : 'tax_percentage', 'discount_pct' : 'discount_percentage'})
df.columns

Index(['customer_id', 'gender', 'location', 'tenure_months', 'transaction_id',
       'transaction_date', 'product_sku', 'product_name', 'product_category',
       'quantity', 'price', 'delivery_charges', 'coupon_status',
       'tax_percentage', 'date', 'offline_spend', 'online_spend', 'month',
       'coupon_code', 'discount_percentage'],
      dtype='object')

In [40]:
df['coupon_status'].unique()

array(['Used', 'Not Used', 'Clicked'], dtype=object)

In [41]:
df['coupon_status'] = df['coupon_status'].str.replace('Clicked', 'Used', regex= True)

In [42]:
df['coupon_status'].unique()

array(['Used', 'Not Used'], dtype=object)

In [43]:
df.head()

,customer_id,gender,location,tenure_months,transaction_id,transaction_date,product_sku,product_name,product_category,quantity,price,delivery_charges,coupon_status,tax_percentage,date,offline_spend,online_spend,month,coupon_code,discount_percentage
0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,1.0,153.71,6.5,Used,0.1,1/1/2019,4500.0,2424.5,1,ELEC10,10.0
1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,1.0,153.71,6.5,Used,0.1,1/1/2019,4500.0,2424.5,1,ELEC10,10.0
2,17850.0,M,Chicago,12.0,16696.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,2.0,122.77,6.5,Not Used,0.1,1/1/2019,4500.0,2424.5,1,ELEC10,10.0
3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,1.0,81.50,6.5,Used,0.1,1/1/2019,4500.0,2424.5,1,ELEC10,10.0
4,17850.0,M,Chicago,12.0,16700.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,1.0,153.71,6.5,Used,0.1,1/1/2019,4500.0,2424.5,1,ELEC10,10.0

In [44]:
df = df.drop_duplicates()

In [45]:
df

,customer_id,gender,location,tenure_months,transaction_id,transaction_date,product_sku,product_name,product_category,quantity,price,delivery_charges,coupon_status,tax_percentage,date,offline_spend,online_spend,month,coupon_code,discount_percentage
0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,1.0,153.71,6.5,Used,0.10,1/1/2019,4500.0,2424.50,1,ELEC10,10.0
1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,1.0,153.71,6.5,Used,0.10,1/1/2019,4500.0,2424.50,1,ELEC10,10.0
2,17850.0,M,Chicago,12.0,16696.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,2.0,122.77,6.5,Not Used,0.10,1/1/2019,4500.0,2424.50,1,ELEC10,10.0
3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,1.0,81.50,6.5,Used,0.10,1/1/2019,4500.0,2424.50,1,ELEC10,10.0
4,17850.0,M,Chicago,12.0,16700.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,1.0,153.71,6.5,Used,0.10,1/1/2019,4500.0,2424.50,1,ELEC10,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52919,13155.0,F,California,8.0,22504.0,2019-03-10,GGOEGGCX056399,Gift Card - $250.00,Gift Cards,1.0,250.00,0.0,Used,0.05,3/10/2019,2500.0,1294.22,3,GC30,30.0
52920,18077.0,M,Chicago,34.0,24250.0,2019-03-28,GGOEGGCX056299,Gift Card - $25.00,Gift Cards,1.0,25.00,0.0,Used,0.05,3/28/2019,2000.0,1066.12,3,GC30,30.0
52921,16085.0,M,California,15.0,39991.0,2019-10-06,GGOEGOCD078399,Google Leather Perforated Journal,Notebooks & Journals,1.0,10.80,6.0,Used,0.05,10/6/2019,3000.0,2230.76,10,NJ10,10.0
52922,16085.0,M,California,15.0,39991.0,2019-10-06,GGOEGOCR078499,Google Spiral Leather Journal,Notebooks & Journals,1.0,9.60,6.0,Used,0.05,10/6/2019,3000.0,2230.76,10,NJ10,10.0
52923,13659.0,F,Chicago,8.0,39998.0,2019-10-06,GGOEGOCC077999,Google Spiral Journal with Pen,Notebooks & Journals,1.0,5.59,6.5,Not Used,0.05,10/6/2019,3000.0,2230.76,10,NJ10,10.0

In [46]:
import pymysql
import sqlalchemy

In [47]:
from sqlalchemy import create_engine

# MySQL connection
username = 
password = 
host = 
port = 
database = 

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

# Write DataFrame to MySQL
table_name = "performance"  # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

# Read back sample
pd.read_sql("SELECT * FROM performance LIMIT 5;", engine)

,customer_id,gender,location,tenure_months,transaction_id,transaction_date,product_sku,product_name,product_category,quantity,price,delivery_charges,coupon_status,tax_percentage,date,offline_spend,online_spend,month,coupon_code,discount_percentage
0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,1.0,153.71,6.5,Used,0.1,1/1/2019,4500.0,2424.5,1,ELEC10,10.0
1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,1.0,153.71,6.5,Used,0.1,1/1/2019,4500.0,2424.5,1,ELEC10,10.0
2,17850.0,M,Chicago,12.0,16696.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,2.0,122.77,6.5,Not Used,0.1,1/1/2019,4500.0,2424.5,1,ELEC10,10.0
3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,1.0,81.50,6.5,Used,0.1,1/1/2019,4500.0,2424.5,1,ELEC10,10.0
4,17850.0,M,Chicago,12.0,16700.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,1.0,153.71,6.5,Used,0.1,1/1/2019,4500.0,2424.5,1,ELEC10,10.0